octopus:
  # If Octopus finds the directive replicated: true, it will assume all shards as slaves, 
  # and the database specified in database.yml as master 
  replicated: true
  environments:
    - development
    - production
  development:
    slave1:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: scoreranking-api_development
      pool: 5
      username: root
      password:
      socket: /tmp/mysql.sock2
  production:
    slave1:
      adapter: mysql2
      database: ranking
      username: deploy
      password: 'Q08f14qgk7'
      host: 'ip-172-31-21-171.ap-northeast-1.compute.internal'
      reconnect: true
